version: "1.0"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
          - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: boardDB
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456

#  app:
#    depends_on:
#      - db
#    image: wordpress:latest
#    volumes:
#      - ./app_data:/var/www/html
#    ports:
#      - "8080:80"
#    restart: always
#    environment:
#      WORDPRESS_DB_HOST: db:3306
#      WORDPRESS_DB_NAME: wordpress
#      WORDPRESS_DB_USER: wordpress_user
#      WORDPRESS_DB_PASSWORD: 123456